---

- name: restart redis
  runit:
    name={{ redis_service_name }}
    state=up
    timeout={{ redis_service_timeout }}
    action=restart
  when: redis_service_status is defined and not redis_service_status.restarted

